### ISSUE TITLE
http://steamcommunity.com/sharedfiles/filedetails/?id=407158161

### ISSUE THREAD

**Issue by CodyJamesCasey** [TheLastBastion/se-scripts#1]

**Comment by MistaLemur** [comment]
I like this script but definitely not run on a timer that triggers itself. I generally prefer to run this off of a button (only when it's needed) or on a 10+ second timer.

**Comment by MistaLemur** [comment]
So I'm okay with approving this script, version 1 or version 2, so long as we have the rule that the script is not allowed to be run more than once per second.

**Comment by MistaLemur** [comment]
I went ahead and added Version 1 of the AutoConfigLCDs script to suggested scripts.

**Comment by CodyJamesCasey** [comment]
I went through the code for v1 and nothing looked too crazy. I think it's probz fine. I wonder if we should do some stress testing? Thoughts?

**Comment by rwicklin** [comment]
Yeah I'm okay with this but not run very frequently. I like the button suggestion, but it seems like an arbitrary rule that might be difficult to enforce. Might be good to stress test a bit on some smaller multiplayer runs (ie one of our computers) to see what a good threshold for any timer block usage might be - like how frequent is too frequent - before committing to server implementation.

**Comment by MistaLemur** [comment]
Since we haven't found a time to test this yet in multiplayer with different timer durations, I am permitting my faction to run the script not on a timer, but only by manually with button press only when needed, since that seems to be approved by everyone else here. IMO, 10 seconds is a good minimum timer duration for running this script.

Once we come to a consensus on what a good minimum timer rate is for this script, I'll move it into fully approved and write up instructions with that minimum timer rate, and let Ori know what's going on I guess.

**Comment by MistaLemur** [comment]
Script has been approved for V1 and V2.
